#!/bin/bash

echo "Running git pre-push hook"

dart format .
flutter analyze .

RESULT=$?

# return 1 exit code if running checks fails
[ $RESULT -ne 0 ] && echo "ERROR: dart format and/or flutter analyze failed. Please fix the issues and re-commit." &&  exit 1
exit 0
