name: pollen_meter
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  json_annotation: ^4.7.0

  cupertino_icons: ^1.0.5
  firebase_core: ^2.9.0
  firebase_analytics: ^10.2.0
  firebase_auth: ^4.4.1
  cloud_firestore: ^4.5.1
  firebase_crashlytics: ^3.1.0
  dio: ^5.1.1
  gauge_indicator: ^0.3.3
  go_router: ^6.5.6
  convex_bottom_bar: ^3.2.0
  shared_preferences: ^2.1.0
  flutter_riverpod: ^2.3.4
  get_it: ^7.2.0

  flutterfire_ui: ^0.4.3+20
  google_sign_in: ^5.4.4
  location: ^4.4.0
  google_fonts: ^4.0.3
  group_button: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  json_serializable: ^6.5.4
  build_runner: ^2.3.3
  intl: ^0.17.0
  intl_translation: ^0.18.0


flutter:


  uses-material-design: true
  generate: true

  assets:
    - assets/images/pollen/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
