// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzUReYoPWDPWIzwfjfOpPvgTUhBKZERm8',
    appId: '1:374533370010:web:24ec68de19732c1dc16f23',
    messagingSenderId: '374533370010',
    projectId: 'pollenmeter-4e79c',
    authDomain: 'pollenmeter-4e79c.firebaseapp.com',
    storageBucket: 'pollenmeter-4e79c.appspot.com',
    measurementId: 'G-1ESN6CDBRE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJMVMruidhNC-qxjKoA6LNNQUJaLKDvbc',
    appId: '1:374533370010:android:fa139f6ccd4440d9c16f23',
    messagingSenderId: '374533370010',
    projectId: 'pollenmeter-4e79c',
    storageBucket: 'pollenmeter-4e79c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzga1rMPGmwtINsMeJ7mpjNMtPtBSuqwg',
    appId: '1:374533370010:ios:ffce8909dc79fcd8c16f23',
    messagingSenderId: '374533370010',
    projectId: 'pollenmeter-4e79c',
    storageBucket: 'pollenmeter-4e79c.appspot.com',
    iosClientId:
        '374533370010-tlvl05s6fp0rg5vh340ijr9p7ftl77p4.apps.googleusercontent.com',
    iosBundleId: 'com.example.pollenMeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzga1rMPGmwtINsMeJ7mpjNMtPtBSuqwg',
    appId: '1:374533370010:ios:ffce8909dc79fcd8c16f23',
    messagingSenderId: '374533370010',
    projectId: 'pollenmeter-4e79c',
    storageBucket: 'pollenmeter-4e79c.appspot.com',
    iosClientId:
        '374533370010-tlvl05s6fp0rg5vh340ijr9p7ftl77p4.apps.googleusercontent.com',
    iosBundleId: 'com.example.pollenMeter',
  );
}
