name: Build CI

on:
  push:
    branches:
      - master

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: run formatter
        run: dart format --set-exit-if-changed .

      - name: Create gson_services.json
        run: touch ./android/app/google-services.json | base64

      - name: Putting data to google_services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > ./android/app/google-services.json

      - name: Putting data to api_token
        env:
          DATA: ${{ secrets.API_KEY }}
        run: echo $DATA > ./lib/core/data/ambee_api/api_token.dart

      - name: run linter
        run: flutter analyze

      - name: build apk
        run: |
          flutter pub get
          flutter build apk

      - name: upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: build/app/outputs/flutter-apk/app-release.apk