name: build trunk

on:
  pull_request:
    types: [opened, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: run formatter
        run: dart format --set-exit-if-changed .

      - name: run linter
        run: flutter analyze
