name: Release CI

on:
  push:
    branches:
      - 'release*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3

      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: run formatter
        run: dart format --set-exit-if-changed .

      - name: run linter
        run: flutter analyze

      - name: Create gson_services.json
        run: cat /home/runner/work/PollenMeter/PollenMeter/app/google-services.json | base64

      - name: Putting data
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > /home/runner/work/PollenMeter/PollenMeter/app/google-services.json


      - name: build apk
        run: |
          flutter pub get
          flutter build apk

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: build/app/outputs/flutter-apk/app-release.apk
